name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.2.5
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^5.1.1
  flutter_local_notifications: ^14.0.0+1
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  package_info_plus: ^3.0.1
#  open_file: ^3.2.2
  sensors_plus: ^2.0.1
  share_plus: ^6.2.0
  better_player: 
    git: https://github.com/a7med-3laa/betterplayer.git
  collection: ^1.17.0
  chopper: ^4.0.6

dev_dependencies:
  lint: ^1.8.2
